### ISSUE TITLE
How to modify the dialog's style?

### ISSUE THREAD

**Issue by carvenl** [ThomasLeconte/vuetify3-dialog#17]
Excellent component. 
How should I modify the dialog's style? For example, remove the icon from the card title bar and align the buttons to the right in the card actions bar.
Thanks.

**Comment by ThomasLeconte** [comment]
Hi, sorry for delay i did not received notification 😅 
You can make a custom component to show instead of my dialog component, please read README at this chapter : https://github.com/ThomasLeconte/vuetify3-dialog?tab=readme-ov-file#new-v140

Moreover, in cardOptions, you can set content of Vuetify's card slots programmatically. A little weird, but it's work !

If you have suggestions to improve library with your issue, don't hesitate to implement it !
