### ISSUE TITLE
vuetify 3.3.4 Not compatible?

### ISSUE THREAD

**Issue by JunwayGuo** [ThomasLeconte/vuetify3-dialog#8]
![image](https://github.com/ThomasLeconte/vuetify3-dialog/assets/31336068/e2a82909-91dc-47d9-b5bc-5f5801b0faa9)

**Comment by ThomasLeconte** [comment]
Hi, Vuetify 3.3.4 was with a lot of "labs" components (and with bugs too), including BottomSheet component. With last version 3.4.0, all last labs components have been fixed of their bugs, so they have been moved from "labs" directory to "lib" directory of Vuetify. That's why the import not work in your case 😉I finally choose to install v3.4.0 to prevent users from bugs, you can see It in package.json of projet 😉

**Comment by ThomasLeconte** [comment]
Vuetify v3.4.0 is so much better, install It if you can 😉 (or new update if available)

**Comment by JunwayGuo** [comment]
Yes, thank you very much, I have upgraded to 3.4.0
